# values.yaml
replicaCount: 3

image:
  repository: "younghak9905/my-app"
  tag: 8ab96a6e324a49ccf65e284e3fae389171f777e2
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30000

containerPort: 80

appName: "my-app"


hpa:
  deployName: "my-app-deployment"
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 50  # CPU 사용률 기준 50%를 목표로 설정
