# values.yaml
replicaCount: 3

image:
  repository: "younghak9905/my-app"
  tag: 7aee98b2abb47aab11f7fe3d63dcc04d23be8106
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30000

containerPort: 80

appName: "my-app"

