# values.yaml
replicaCount: 3

image:
  repository: "younghak9905/my-app"
  tag: ac8787a03f62309c03a6948c2b27b3613e0255d6
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30000

containerPort: 80

appName: "my-app"

